[package]
name = "strata"
version = "0.0.1"
edition = "2021"
authors = ["Anant Narayan <anantnrg@gmail.com>"]
license = "GNU GPL v3"
description = "A modular, dynamic and sleek Wayland compositor with batteries included."
readme = "README.md"
homepage = "https://github.com/stratawm/strata"
repository = "https://github.com/stratawm/strata"
keywords = ["smithay", "compositor", "wayland", "linux", "linux-utilities", "wm", "windows", "manager"]
categories = ["linux-utilities"]


[dependencies]
tracing-subscriber = {features = ["env-filter"], version = "0.3.17"}
bitflags = "2.2.1"
toml = "0.7.4"
serde_derive = "1.0.164"
dirs = "5.0.1"
colored = "2.0.0"
clap = { version = "4.3.11", features = ["derive"] }

[dependencies.smithay]
git = "https://github.com/smithay/smithay"
version = "0.3"
rev = "bb451a5"
